[project]
name = "valdac"
version = "0.2.0"
description = "validation for data classes"
readme = "README.md"
package-mode = true
packages = [{include = "valdac", from = "src"}]
requires-python = "<3.12.0a1,>=3.11"
authors = [
    {name = "Rama Krishna", email = ""},
]
include = ["src/valdac/py.typed"]


dependencies = [
    "beartype>=0.21.0",
    "dataclasses-json>=0.6.7",
    "pydantic>=2.11.7",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
